# csa-atrophy pipeline parameters

# process_data.sh parameters
n_transfo: 2
rescaling:
  - 0.95
  - 1.00
contrast: "t2"

# manual_labeling_correction.sh parameters
FILES_SEGMANUAL:
#  - "sub-amu01_T2w_r0.9_t1.nii.gz"
  - "sub-amu01_T2w_r0.95_t2.nii.gz"
PATH_ORIGINAL_RESULTS: "csa_atrophy_results_t2/results"
PATH_ORIGINAL_CSV: "csa_atrophy_results_t2/data_processed"
PATH_DESTINATION_RESULTS: "csa_atrophy_results_corrected2/results"
PATH_SEGMANUAL: "csa_atrophy_results_corrected2/derivatives"

# csa_atrophy_stat.py parameters
stats:
  sample_size:
    atrophy_sample: 7.7
    conf: 0.95
    power: 0.8

# affine_transfo.py parameters
transfo:
  bounds:
    angle_bound: 5
    shift_bound: 2.5
    
# config file for sct_run_batch
path_data   : "data"
path_output : "csa_atrophy_results_t2"
script      : "process_data.sh"
jobs        : -1
